export enum MovieGenre {
    ACTION = "Action",
    ADVENTURE = "Adventure",
    SCIENCE_FICTION = "Science Fiction",
    COMEDY = "Comedy",
    DRAMA = "Drama",
    ROMANCE = "Romance",
    HORROR = "Horror",
    SUSPENSE = "Suspense",
    ANIMATION = "Animation",
    FANTASY = "Fantasy",
    CRIME = "Crime",
    MYSTERY = "Mystery",
    DOCUMENTARY = "Documentary",
    MUSICAL = "Musical",
    WESTERN = "Western",
    WAR = "War",
    HISTORICAL = "Historical",
    BIOGRAPHY = "Biography",
    SPORT = "Sport",
    FAMILY = "Family",
    SCIENCE_FANTASY = "Science Fantasy",
    SUPERHEROES = "Superheroes",
    THRILLER = "Thriller",
    NOIR = "Noir",
    MARTIAL_ARTS = "Martial Arts"
}